title: Julia Tilinga
remote_theme: just-the-docs/just-the-docs

# Настройки сайдбара (автоматическая иерархия)
search_enabled: true
heading_anchors: true

# Папка с твоими md-файлами
collections:
  docs:
    permalink: "/:path/"
    output: true

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"