site_name: Julia Tilinga

theme:
  name: material
  palette:
    primary: custom
  custom_dir: overrides
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.jpg
  features:
    - navigation.sections
    - navigation.indexes

plugins:
  - search

copyright: '© 1988–2026 Julia Tilinga | <a href="https://music.apple.com/us/artist/julia-tilinga/1752864835" target="_blank" rel="noopener">🅐 Apple Music</a> | <a href="https://open.spotify.com/artist/29Z2YEcTujgk9DreH3sRmC" target="_blank" rel="noopener">🅢 Spotify</a> | <a href="https://music.yandex.com/artist/22514951" target="_blank" rel="noopener">🅨 Yandex Music</a>'

extra_css:
  - assets/stylesheets/extra.css

nav:
  - 'ru':
      - 'По-русски': 'ru/index.md'
      - 'song':
          - 'Песни':
          - "0. You Sang To Me": 'ru/song/you_sang_to_me.md'
          - "1. Первый шаг": 'ru/song/first_step.md'
          - "2. Больно": 'ru/song/it_hurts.md'
          - "3. Touch Me Slow": 'ru/song/touch_me_slow.md'